// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO project (name, root_path)
VALUES (?, ?)
RETURNING id, name, root_path, description, created_at, updated_at
`

type CreateProjectParams struct {
	Name     string
	RootPath string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.Name, arg.RootPath)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RootPath,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByRootPath = `-- name: GetProjectByRootPath :one
SELECT id, name, root_path, description, created_at, updated_at
FROM project
WHERE root_path = ?
`

func (q *Queries) GetProjectByRootPath(ctx context.Context, rootPath string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByRootPath, rootPath)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RootPath,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ping = `-- name: Ping :one
SELECT 1
`

func (q *Queries) Ping(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, ping)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE project
SET name = ?, description = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, root_path, description, created_at, updated_at
`

type UpdateProjectParams struct {
	Name        string
	Description string
	ID          int64
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject, arg.Name, arg.Description, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RootPath,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
