// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
)

const countTasksByProject = `-- name: CountTasksByProject :one
SELECT COUNT(*) FROM task WHERE project_id = ?
`

func (q *Queries) CountTasksByProject(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTasksByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO project (name, root_path)
VALUES (?, ?)
RETURNING id, name, root_path, description, created_at, updated_at
`

type CreateProjectParams struct {
	Name     string
	RootPath string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.Name, arg.RootPath)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RootPath,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO task (project_id, category, description, status)
VALUES (?, ?, ?, ?)
RETURNING id, project_id, category, description, status, progress_report, created_at, updated_at
`

type CreateTaskParams struct {
	ProjectID   int64
	Category    string
	Description string
	Status      string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ProjectID,
		arg.Category,
		arg.Description,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Category,
		&i.Description,
		&i.Status,
		&i.ProgressReport,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTaskStep = `-- name: CreateTaskStep :one
INSERT INTO task_step (task_id, position, description)
VALUES (?, ?, ?)
RETURNING id, task_id, position, description, created_at, updated_at
`

type CreateTaskStepParams struct {
	TaskID      int64
	Position    int64
	Description string
}

func (q *Queries) CreateTaskStep(ctx context.Context, arg CreateTaskStepParams) (TaskStep, error) {
	row := q.db.QueryRowContext(ctx, createTaskStep, arg.TaskID, arg.Position, arg.Description)
	var i TaskStep
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Position,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTaskStepsByProject = `-- name: DeleteTaskStepsByProject :exec
DELETE FROM task_step
WHERE task_id IN (SELECT id FROM task WHERE project_id = ?)
`

func (q *Queries) DeleteTaskStepsByProject(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTaskStepsByProject, projectID)
	return err
}

const deleteTasksByProject = `-- name: DeleteTasksByProject :exec
DELETE FROM task WHERE project_id = ?
`

func (q *Queries) DeleteTasksByProject(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTasksByProject, projectID)
	return err
}

const getProjectByRootPath = `-- name: GetProjectByRootPath :one
SELECT id, name, root_path, description, created_at, updated_at
FROM project
WHERE root_path = ?
`

func (q *Queries) GetProjectByRootPath(ctx context.Context, rootPath string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByRootPath, rootPath)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RootPath,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ping = `-- name: Ping :one
SELECT 1
`

func (q *Queries) Ping(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, ping)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE project
SET name = ?, description = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, root_path, description, created_at, updated_at
`

type UpdateProjectParams struct {
	Name        string
	Description string
	ID          int64
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject, arg.Name, arg.Description, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RootPath,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
