// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countTasksByProject = `-- name: CountTasksByProject :one
SELECT COUNT(*) FROM task WHERE project_id = ?
`

func (q *Queries) CountTasksByProject(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTasksByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProgress = `-- name: CreateProgress :one
INSERT INTO progress (project_id, task_id, run_id, summary)
VALUES (?, ?, ?, ?)
RETURNING id, project_id, task_id, run_id, summary, created_at, updated_at
`

type CreateProgressParams struct {
	ProjectID int64
	TaskID    sql.NullInt64
	RunID     sql.NullInt64
	Summary   string
}

func (q *Queries) CreateProgress(ctx context.Context, arg CreateProgressParams) (Progress, error) {
	row := q.db.QueryRowContext(ctx, createProgress,
		arg.ProjectID,
		arg.TaskID,
		arg.RunID,
		arg.Summary,
	)
	var i Progress
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.RunID,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO project (name, root_path)
VALUES (?, ?)
RETURNING id, name, root_path, description, created_at, updated_at
`

type CreateProjectParams struct {
	Name     string
	RootPath string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.Name, arg.RootPath)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RootPath,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO run (project_id, task_id, runner_name, status, host, started_at, heartbeat_at)
VALUES (?, ?, ?, 'running', ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, project_id, task_id, runner_name, runner_version, runner_model, session_id, session_path, status, exit_code, exit_signal, exit_error, pid, host, heartbeat_at, started_at, finished_at, created_at, updated_at
`

type CreateRunParams struct {
	ProjectID  int64
	TaskID     sql.NullInt64
	RunnerName string
	Host       string
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, createRun,
		arg.ProjectID,
		arg.TaskID,
		arg.RunnerName,
		arg.Host,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.RunnerName,
		&i.RunnerVersion,
		&i.RunnerModel,
		&i.SessionID,
		&i.SessionPath,
		&i.Status,
		&i.ExitCode,
		&i.ExitSignal,
		&i.ExitError,
		&i.Pid,
		&i.Host,
		&i.HeartbeatAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO task (project_id, category, description, status)
VALUES (?, ?, ?, ?)
RETURNING id, project_id, category, description, status, progress_report, created_at, updated_at
`

type CreateTaskParams struct {
	ProjectID   int64
	Category    string
	Description string
	Status      string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ProjectID,
		arg.Category,
		arg.Description,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Category,
		&i.Description,
		&i.Status,
		&i.ProgressReport,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTaskStep = `-- name: CreateTaskStep :one
INSERT INTO task_step (task_id, position, description)
VALUES (?, ?, ?)
RETURNING id, task_id, position, description, created_at, updated_at
`

type CreateTaskStepParams struct {
	TaskID      int64
	Position    int64
	Description string
}

func (q *Queries) CreateTaskStep(ctx context.Context, arg CreateTaskStepParams) (TaskStep, error) {
	row := q.db.QueryRowContext(ctx, createTaskStep, arg.TaskID, arg.Position, arg.Description)
	var i TaskStep
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Position,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTaskStepsByProject = `-- name: DeleteTaskStepsByProject :exec
DELETE FROM task_step
WHERE task_id IN (SELECT id FROM task WHERE project_id = ?)
`

func (q *Queries) DeleteTaskStepsByProject(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTaskStepsByProject, projectID)
	return err
}

const deleteTaskStepsByTask = `-- name: DeleteTaskStepsByTask :exec
DELETE FROM task_step
WHERE task_id = ?
`

func (q *Queries) DeleteTaskStepsByTask(ctx context.Context, taskID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTaskStepsByTask, taskID)
	return err
}

const deleteTasksByProject = `-- name: DeleteTasksByProject :exec
DELETE FROM task WHERE project_id = ?
`

func (q *Queries) DeleteTasksByProject(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTasksByProject, projectID)
	return err
}

const finishRun = `-- name: FinishRun :one
UPDATE run
SET runner_name = ?,
    runner_version = ?,
    runner_model = ?,
    session_id = ?,
    session_path = ?,
    status = ?,
    exit_code = ?,
    exit_signal = ?,
    exit_error = ?,
    pid = ?,
    host = ?,
    heartbeat_at = CURRENT_TIMESTAMP,
    finished_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE project_id = ? AND id = ?
RETURNING id, project_id, task_id, runner_name, runner_version, runner_model, session_id, session_path, status, exit_code, exit_signal, exit_error, pid, host, heartbeat_at, started_at, finished_at, created_at, updated_at
`

type FinishRunParams struct {
	RunnerName    string
	RunnerVersion string
	RunnerModel   string
	SessionID     string
	SessionPath   string
	Status        string
	ExitCode      sql.NullInt64
	ExitSignal    sql.NullString
	ExitError     sql.NullString
	Pid           sql.NullInt64
	Host          string
	ProjectID     int64
	ID            int64
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, finishRun,
		arg.RunnerName,
		arg.RunnerVersion,
		arg.RunnerModel,
		arg.SessionID,
		arg.SessionPath,
		arg.Status,
		arg.ExitCode,
		arg.ExitSignal,
		arg.ExitError,
		arg.Pid,
		arg.Host,
		arg.ProjectID,
		arg.ID,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.RunnerName,
		&i.RunnerVersion,
		&i.RunnerModel,
		&i.SessionID,
		&i.SessionPath,
		&i.Status,
		&i.ExitCode,
		&i.ExitSignal,
		&i.ExitError,
		&i.Pid,
		&i.Host,
		&i.HeartbeatAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveRunByProject = `-- name: GetActiveRunByProject :one
SELECT id, project_id, task_id, runner_name, runner_version, runner_model, session_id, session_path, status, exit_code, exit_signal, exit_error, pid, host, heartbeat_at, started_at, finished_at, created_at, updated_at
FROM run
WHERE project_id = ? AND status = 'running'
ORDER BY COALESCE(started_at, created_at) DESC, id DESC
LIMIT 1
`

func (q *Queries) GetActiveRunByProject(ctx context.Context, projectID int64) (Run, error) {
	row := q.db.QueryRowContext(ctx, getActiveRunByProject, projectID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.RunnerName,
		&i.RunnerVersion,
		&i.RunnerModel,
		&i.SessionID,
		&i.SessionPath,
		&i.Status,
		&i.ExitCode,
		&i.ExitSignal,
		&i.ExitError,
		&i.Pid,
		&i.Host,
		&i.HeartbeatAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextEligibleTaskByProject = `-- name: GetNextEligibleTaskByProject :one
SELECT id, project_id, category, description, status, progress_report, created_at, updated_at
FROM task
WHERE project_id = ? AND status IN ('pending', 'failed')
ORDER BY id
LIMIT 1
`

func (q *Queries) GetNextEligibleTaskByProject(ctx context.Context, projectID int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getNextEligibleTaskByProject, projectID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Category,
		&i.Description,
		&i.Status,
		&i.ProgressReport,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByRootPath = `-- name: GetProjectByRootPath :one
SELECT id, name, root_path, description, created_at, updated_at
FROM project
WHERE root_path = ?
`

func (q *Queries) GetProjectByRootPath(ctx context.Context, rootPath string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByRootPath, rootPath)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RootPath,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunByProjectAndID = `-- name: GetRunByProjectAndID :one
SELECT id, project_id, task_id, runner_name, runner_version, runner_model, session_id, session_path, status, exit_code, exit_signal, exit_error, pid, host, heartbeat_at, started_at, finished_at, created_at, updated_at
FROM run
WHERE project_id = ? AND id = ?
`

type GetRunByProjectAndIDParams struct {
	ProjectID int64
	ID        int64
}

func (q *Queries) GetRunByProjectAndID(ctx context.Context, arg GetRunByProjectAndIDParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRunByProjectAndID, arg.ProjectID, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.RunnerName,
		&i.RunnerVersion,
		&i.RunnerModel,
		&i.SessionID,
		&i.SessionPath,
		&i.Status,
		&i.ExitCode,
		&i.ExitSignal,
		&i.ExitError,
		&i.Pid,
		&i.Host,
		&i.HeartbeatAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByProjectAndID = `-- name: GetTaskByProjectAndID :one
SELECT id, project_id, category, description, status, progress_report, created_at, updated_at
FROM task
WHERE project_id = ? AND id = ?
`

type GetTaskByProjectAndIDParams struct {
	ProjectID int64
	ID        int64
}

func (q *Queries) GetTaskByProjectAndID(ctx context.Context, arg GetTaskByProjectAndIDParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByProjectAndID, arg.ProjectID, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Category,
		&i.Description,
		&i.Status,
		&i.ProgressReport,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLatestProgressByTask = `-- name: ListLatestProgressByTask :many
SELECT id, project_id, task_id, run_id, summary, created_at, updated_at
FROM progress
WHERE task_id = ?
ORDER BY created_at DESC, id DESC
LIMIT ?
`

type ListLatestProgressByTaskParams struct {
	TaskID sql.NullInt64
	Limit  int64
}

func (q *Queries) ListLatestProgressByTask(ctx context.Context, arg ListLatestProgressByTaskParams) ([]Progress, error) {
	rows, err := q.db.QueryContext(ctx, listLatestProgressByTask, arg.TaskID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Progress
	for rows.Next() {
		var i Progress
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskID,
			&i.RunID,
			&i.Summary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgressByProject = `-- name: ListProgressByProject :many
SELECT id, project_id, task_id, run_id, summary, created_at, updated_at
FROM progress
WHERE project_id = ?
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListProgressByProject(ctx context.Context, projectID int64) ([]Progress, error) {
	rows, err := q.db.QueryContext(ctx, listProgressByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Progress
	for rows.Next() {
		var i Progress
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskID,
			&i.RunID,
			&i.Summary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgressByProjectAndTask = `-- name: ListProgressByProjectAndTask :many
SELECT id, project_id, task_id, run_id, summary, created_at, updated_at
FROM progress
WHERE project_id = ? AND task_id = ?
ORDER BY created_at DESC, id DESC
`

type ListProgressByProjectAndTaskParams struct {
	ProjectID int64
	TaskID    sql.NullInt64
}

func (q *Queries) ListProgressByProjectAndTask(ctx context.Context, arg ListProgressByProjectAndTaskParams) ([]Progress, error) {
	rows, err := q.db.QueryContext(ctx, listProgressByProjectAndTask, arg.ProjectID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Progress
	for rows.Next() {
		var i Progress
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskID,
			&i.RunID,
			&i.Summary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgressByRun = `-- name: ListProgressByRun :many
SELECT id, project_id, task_id, run_id, summary, created_at, updated_at
FROM progress
WHERE project_id = ? AND run_id = ?
ORDER BY created_at DESC, id DESC
`

type ListProgressByRunParams struct {
	ProjectID int64
	RunID     sql.NullInt64
}

func (q *Queries) ListProgressByRun(ctx context.Context, arg ListProgressByRunParams) ([]Progress, error) {
	rows, err := q.db.QueryContext(ctx, listProgressByRun, arg.ProjectID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Progress
	for rows.Next() {
		var i Progress
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskID,
			&i.RunID,
			&i.Summary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByProject = `-- name: ListRunsByProject :many
SELECT id, project_id, task_id, runner_name, runner_version, runner_model, session_id, session_path, status, exit_code, exit_signal, exit_error, pid, host, heartbeat_at, started_at, finished_at, created_at, updated_at
FROM run
WHERE project_id = ?
ORDER BY COALESCE(started_at, created_at) DESC, id DESC
`

func (q *Queries) ListRunsByProject(ctx context.Context, projectID int64) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskID,
			&i.RunnerName,
			&i.RunnerVersion,
			&i.RunnerModel,
			&i.SessionID,
			&i.SessionPath,
			&i.Status,
			&i.ExitCode,
			&i.ExitSignal,
			&i.ExitError,
			&i.Pid,
			&i.Host,
			&i.HeartbeatAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskPRDRowsByProject = `-- name: ListTaskPRDRowsByProject :many
SELECT
    t.id,
    t.category,
    t.description,
    t.status,
    ts.description AS step_description
FROM task t
LEFT JOIN task_step ts ON ts.task_id = t.id
WHERE t.project_id = ?
ORDER BY t.id, ts.position
`

type ListTaskPRDRowsByProjectRow struct {
	ID              int64
	Category        string
	Description     string
	Status          string
	StepDescription sql.NullString
}

func (q *Queries) ListTaskPRDRowsByProject(ctx context.Context, projectID int64) ([]ListTaskPRDRowsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listTaskPRDRowsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskPRDRowsByProjectRow
	for rows.Next() {
		var i ListTaskPRDRowsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Description,
			&i.Status,
			&i.StepDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskStepsByTask = `-- name: ListTaskStepsByTask :many
SELECT id, task_id, position, description, created_at, updated_at
FROM task_step
WHERE task_id = ?
ORDER BY position
`

func (q *Queries) ListTaskStepsByTask(ctx context.Context, taskID int64) ([]TaskStep, error) {
	rows, err := q.db.QueryContext(ctx, listTaskStepsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskStep
	for rows.Next() {
		var i TaskStep
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Position,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT id, project_id, category, description, status, progress_report, created_at, updated_at
FROM task
WHERE project_id = ?
ORDER BY id
`

func (q *Queries) ListTasksByProject(ctx context.Context, projectID int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Category,
			&i.Description,
			&i.Status,
			&i.ProgressReport,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProjectAndStatus = `-- name: ListTasksByProjectAndStatus :many
SELECT id, project_id, category, description, status, progress_report, created_at, updated_at
FROM task
WHERE project_id = ? AND status = ?
ORDER BY id
`

type ListTasksByProjectAndStatusParams struct {
	ProjectID int64
	Status    string
}

func (q *Queries) ListTasksByProjectAndStatus(ctx context.Context, arg ListTasksByProjectAndStatusParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByProjectAndStatus, arg.ProjectID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Category,
			&i.Description,
			&i.Status,
			&i.ProgressReport,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ping = `-- name: Ping :one
SELECT 1
`

func (q *Queries) Ping(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, ping)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setRunTaskID = `-- name: SetRunTaskID :one
UPDATE run
SET task_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE project_id = ? AND id = ?
RETURNING id, project_id, task_id, runner_name, runner_version, runner_model, session_id, session_path, status, exit_code, exit_signal, exit_error, pid, host, heartbeat_at, started_at, finished_at, created_at, updated_at
`

type SetRunTaskIDParams struct {
	TaskID    sql.NullInt64
	ProjectID int64
	ID        int64
}

func (q *Queries) SetRunTaskID(ctx context.Context, arg SetRunTaskIDParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, setRunTaskID, arg.TaskID, arg.ProjectID, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.RunnerName,
		&i.RunnerVersion,
		&i.RunnerModel,
		&i.SessionID,
		&i.SessionPath,
		&i.Status,
		&i.ExitCode,
		&i.ExitSignal,
		&i.ExitError,
		&i.Pid,
		&i.Host,
		&i.HeartbeatAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE project
SET name = ?, description = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, root_path, description, created_at, updated_at
`

type UpdateProjectParams struct {
	Name        string
	Description string
	ID          int64
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject, arg.Name, arg.Description, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RootPath,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE task
SET category = ?, description = ?, status = ?, progress_report = ?, updated_at = CURRENT_TIMESTAMP
WHERE project_id = ? AND id = ?
RETURNING id, project_id, category, description, status, progress_report, created_at, updated_at
`

type UpdateTaskParams struct {
	Category       string
	Description    string
	Status         string
	ProgressReport string
	ProjectID      int64
	ID             int64
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.Category,
		arg.Description,
		arg.Status,
		arg.ProgressReport,
		arg.ProjectID,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Category,
		&i.Description,
		&i.Status,
		&i.ProgressReport,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
